import { BookOpen, Target, Sun, ChatsCircle, Notebook, Brain, TrendUp, Eye, Wrench } from '@phosphor-icons/react';

const GOLD = '#D4A853';
const GOLD_DARK = '#9A6B1F';
const GOLD_GRADIENT = 'linear-gradient(90deg, #D4A853, #E8C260)';
const HEADER_GRADIENT = 'linear-gradient(135deg, #1C1917 0%, #292524 100%)';

export const MODE_THEMES = {
  learn: {
    key: 'learn',
    name: 'Learn',
    icon: BookOpen,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFFBEB 0%, #FEF3C7 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Knowledge',
    description: '38 lessons across 5 difficulty tiers',
    path: '/mode/learn',
  },
  practice: {
    key: 'practice',
    name: 'Practice',
    icon: Target,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFF8ED 0%, #FFEDD5 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Skills',
    description: '80+ scenarios across 10 categories',
    path: '/mode/practice',
  },
  daily: {
    key: 'daily',
    name: 'Daily Challenge',
    icon: Sun,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFFDF8 0%, #FEF9EE 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Habits',
    description: '60 daily challenges',
    path: '/mode/daily',
  },
  simulate: {
    key: 'simulate',
    name: 'Simulate',
    icon: ChatsCircle,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FEF3C7 0%, #FDE68A 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Immersion',
    description: '15 immersive conversations',
    path: '/mode/simulate',
  },
  pattern: {
    key: 'pattern',
    name: 'Pattern Hub',
    icon: Eye,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FEFCE8 0%, #FEF9C3 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Perception',
    description: '5 pattern recognition drills',
    path: '/mode/pattern',
  },
  technique: {
    key: 'technique',
    name: 'Technique Drill',
    icon: Wrench,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFF7ED 0%, #FED7AA 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Mastery',
    description: '4 core techniques — learn, drill, master',
    path: '/mode/technique',
  },
  journal: {
    key: 'journal',
    name: 'Journal',
    icon: Notebook,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FAFAF9 0%, #FFF8F0 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Reflection',
    description: 'Log your real questions',
    path: '/journal',
  },
  review: {
    key: 'review',
    name: 'Review',
    icon: Brain,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFFBF4 0%, #FEF3C7 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Memory',
    description: '200+ spaced repetition flashcards',
    path: '/mode/review',
  },
  progress: {
    key: 'progress',
    name: 'Progress',
    icon: TrendUp,
    primary: GOLD,
    secondary: GOLD_DARK,
    gradient: GOLD_GRADIENT,
    headerGradient: HEADER_GRADIENT,
    bgGradient: 'linear-gradient(180deg, #FFEDD5 0%, #FCA14A 100%)',
    cardBg: '#FFFFFF',
    textOnGradient: '#FFFFFF',
    accent: GOLD_DARK,
    category: 'Achievement',
    description: 'Track your growth',
    path: '/progress',
  },
};

export const MODE_LIST = Object.values(MODE_THEMES);
export const PLAYABLE_MODES = MODE_LIST.filter(m => !['progress', 'journal'].includes(m.key));
