import { BookOpen, Target, Sun, ChatsCircle, Notebook, Brain, TrendUp, Eye } from '@phosphor-icons/react';

export const MODE_THEMES = {
  learn: {
    key: 'learn',
    name: 'Learn',
    icon: BookOpen,
    primary: '#F59E0B',
    secondary: '#D97706',
    gradient: 'linear-gradient(135deg, #F59E0B 0%, #D97706 50%, #B45309 100%)',
    bgGradient: 'linear-gradient(180deg, #FEF3C7 0%, #FDE68A 100%)',
    cardBg: '#FFFBEB',
    textOnGradient: '#FFFFFF',
    accent: '#92400E',
    category: 'Knowledge',
    description: '38 lessons across 5 difficulty tiers',
    path: '/mode/learn',
  },
  practice: {
    key: 'practice',
    name: 'Practice',
    icon: Target,
    primary: '#EF4444',
    secondary: '#DC2626',
    gradient: 'linear-gradient(135deg, #EF4444 0%, #DC2626 50%, #B91C1C 100%)',
    bgGradient: 'linear-gradient(180deg, #FEE2E2 0%, #FECACA 100%)',
    cardBg: '#FFF5F5',
    textOnGradient: '#FFFFFF',
    accent: '#991B1B',
    category: 'Skills',
    description: '80+ scenarios across 10 categories',
    path: '/mode/practice',
  },
  daily: {
    key: 'daily',
    name: 'Daily Challenge',
    icon: Sun,
    primary: '#10B981',
    secondary: '#059669',
    gradient: 'linear-gradient(135deg, #10B981 0%, #059669 50%, #047857 100%)',
    bgGradient: 'linear-gradient(180deg, #D1FAE5 0%, #A7F3D0 100%)',
    cardBg: '#F0FDF4',
    textOnGradient: '#FFFFFF',
    accent: '#065F46',
    category: 'Habits',
    description: '60 daily challenges',
    path: '/mode/daily',
  },
  simulate: {
    key: 'simulate',
    name: 'Simulate',
    icon: ChatsCircle,
    primary: '#8B5CF6',
    secondary: '#7C3AED',
    gradient: 'linear-gradient(135deg, #8B5CF6 0%, #7C3AED 50%, #6D28D9 100%)',
    bgGradient: 'linear-gradient(180deg, #EDE9FE 0%, #DDD6FE 100%)',
    cardBg: '#F5F3FF',
    textOnGradient: '#FFFFFF',
    accent: '#5B21B6',
    category: 'Immersion',
    description: '15 immersive conversations',
    path: '/mode/simulate',
  },
  pattern: {
    key: 'pattern',
    name: 'Pattern Hub',
    icon: Eye,
    primary: '#EC4899',
    secondary: '#DB2777',
    gradient: 'linear-gradient(135deg, #EC4899 0%, #DB2777 50%, #BE185D 100%)',
    bgGradient: 'linear-gradient(180deg, #FCE7F3 0%, #FBCFE8 100%)',
    cardBg: '#FDF2F8',
    textOnGradient: '#FFFFFF',
    accent: '#9D174D',
    category: 'Perception',
    description: '5 pattern recognition drills',
    path: '/mode/pattern',
  },
  journal: {
    key: 'journal',
    name: 'Journal',
    icon: Notebook,
    primary: '#06B6D4',
    secondary: '#0891B2',
    gradient: 'linear-gradient(135deg, #06B6D4 0%, #0891B2 50%, #0E7490 100%)',
    bgGradient: 'linear-gradient(180deg, #CFFAFE 0%, #A5F3FC 100%)',
    cardBg: '#F0FDFA',
    textOnGradient: '#FFFFFF',
    accent: '#155E75',
    category: 'Reflection',
    description: 'Log your real questions',
    path: '/journal',
  },
  review: {
    key: 'review',
    name: 'Review',
    icon: Brain,
    primary: '#3B82F6',
    secondary: '#2563EB',
    gradient: 'linear-gradient(135deg, #3B82F6 0%, #2563EB 50%, #1D4ED8 100%)',
    bgGradient: 'linear-gradient(180deg, #DBEAFE 0%, #BFDBFE 100%)',
    cardBg: '#EFF6FF',
    textOnGradient: '#FFFFFF',
    accent: '#1E40AF',
    category: 'Memory',
    description: '200+ spaced repetition flashcards',
    path: '/mode/review',
  },
  progress: {
    key: 'progress',
    name: 'Progress',
    icon: TrendUp,
    primary: '#F97316',
    secondary: '#EA580C',
    gradient: 'linear-gradient(135deg, #F97316 0%, #EA580C 50%, #C2410C 100%)',
    bgGradient: 'linear-gradient(180deg, #FFEDD5 0%, #FED7AA 100%)',
    cardBg: '#FFF7ED',
    textOnGradient: '#FFFFFF',
    accent: '#9A3412',
    category: 'Achievement',
    description: 'Track your growth',
    path: '/progress',
  },
};

export const MODE_LIST = Object.values(MODE_THEMES);
export const PLAYABLE_MODES = MODE_LIST.filter(m => !['progress', 'journal'].includes(m.key));
